#!/usr/bin/env python3
## EPITECHPROJECT, 2021
## gomoku
## File description:
## AI
##

import sys
import csv
from math import *
#from numpy import *

Map = arr = [['.' for i in range(20)] for j in range(20)]

def help():
    if len(sys.argv) == 2:
        if sys.argv[1] == "-h" or sys.argv[1] == "--help":
            print("USAGE")
            print("\t./pbrain-gomoku-ai\n")
            exit(0)

def printMap():
    print(end="\t")
    for i in range(1, 21):
        print(chr(i + 64), end="\t")
    print()
    for i in range(165):
        print("_", end="")
    print()
    j = 0
    for i in range(20):
        j = 0
        print("%d|\t" %(i+1), end="")
        for j in range(20):
            print(Map[i][j], end="\t")
        print()
    print()

def gomoku():
    global Map
    while(1):
        printMap()
        u_input = input()
        if not u_input[1:].isnumeric() and u_input[0].isnumeric():
            exit(84)
        pos_y = ord(u_input[0])-65
        pos_x = int(u_input[1:]) - 1
        print(pos_x, pos_y)
        Map[pos_x][pos_y] = "X"

def main():
    help()
    gomoku()


if __name__ == "__main__":
    main()
